# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(305, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(240, 440, 151, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 90, 121, 20))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.use_numders = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.use_numders.setGeometry(QtCore.QRect(80, 180, 161, 17))
        self.use_numders.setObjectName("use_numders")
        self.use_letters = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.use_letters.setGeometry(QtCore.QRect(80, 200, 151, 17))
        self.use_letters.setTristate(False)
        self.use_letters.setObjectName("use_letters")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.resuit = QtWidgets.QLabel(parent=self.centralwidget)
        self.resuit.setGeometry(QtCore.QRect(120, 150, 71, 20))
        self.resuit.setObjectName("resuit")
        self.generate_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(110, 290, 91, 23))
        self.generate_btn.setStyleSheet("color: red;\n"
"\n"
"")
        self.generate_btn.setObjectName("generate_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 305, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Генератр паролів"))
        self.use_numders.setText(_translate("MainWindow", "використовувати числа "))
        self.use_letters.setText(_translate("MainWindow", "використовувати алфавіт"))
        self.resuit.setText(_translate("MainWindow", "результат"))
        self.generate_btn.setText(_translate("MainWindow", "згенерувати"))
